name: Food Delivery Production Pipeline

on:
  push:
    branches:
      - master

permissions:
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: food_delivery_time_prediction
  ECR_REGISTRY: 125840290869.dkr.ecr.us-east-1.amazonaws.com
  DAGSHUB_REPO_OWNER: aryanupadhyay23
  DAGSHUB_REPO_NAME: Food-Delivery-Time-prediction
  MLFLOW_TRACKING_URI: https://dagshub.com/aryanupadhyay23/Food-Delivery-Time-prediction.mlflow

jobs:

  ci:
    name: CI - Validate and Promote Model
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python 3.11 with pip cache
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: dev-requirements.txt

      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Lint (Critical Errors Only)
        run: |
          flake8 src inference_app --select=E9,F63,F7,F82 --show-source --statistics

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: DVC Pull
        run: dvc pull

      - name: Promote Model to Staging
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_USERNAME: ${{ env.DAGSHUB_REPO_OWNER }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
        run: python src/models/promote_to_staging.py

      - name: Promote Model to Production
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_USERNAME: ${{ env.DAGSHUB_REPO_OWNER }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
        run: python src/models/promote_to_production.py


  cd:
    name: CD - Build, Test and Push Docker Image
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image (Load Locally)
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Container Integration Test
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          docker run -d --name test_container \
            -p 8000:8000 \
            -e DAGSHUB_TOKEN=$DAGSHUB_TOKEN \
            -e MLFLOW_TRACKING_USERNAME=${{ env.DAGSHUB_REPO_OWNER }} \
            -e MLFLOW_TRACKING_PASSWORD=$DAGSHUB_TOKEN \
            -e MLFLOW_TRACKING_URI=${{ env.MLFLOW_TRACKING_URI }} \
            app:${{ github.sha }}

          for i in {1..20}; do
            sleep 2
            if curl -s http://localhost:8000/health | grep healthy; then
              echo "API healthy"
              break
            fi
          done

          curl --fail http://localhost:8000/health

          docker stop test_container
          docker rm test_container

      - name: Tag Image for ECR
        run: |
          docker tag app:${{ github.sha }} \
            $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}

          docker tag app:${{ github.sha }} \
            $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Push Image to ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.sha }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - name: Zip files for deployment
        if: success()
        run: |
          zip -r deployment.zip appspec.yml deploy/scripts/install_dependencies.sh deploy/scripts/start_docker.sh

      - name: Upload ZIP to S3
        if: success()
        run: |
          aws s3 cp deployment.zip s3://fooddeliverytimepredictiondeployment/deployment.zip

      - name: Deploy to AWS CodeDeploy
        if: success()
        run: |
          aws deploy create-deployment \
            --application-name food-delivery-time-prediction-app \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --deployment-group-name food-delivery-time-prediction-group \
            --s3-location bucket=deliverytimepredictiondeployment,key=deployment.zip,bundleType=zip \
            --file-exists-behavior OVERWRITE \
            --region us-east-1
